# Generated by Django 4.0.5 on 2022-07-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
