# Generated by Django 4.0.6 on 2022-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('student', 'student'), ('lecturer', 'lecturer')], max_length=10, null=True),
        ),
    ]
