# Generated by Django 4.0.6 on 2022-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(default='SCH/FCULT/DPT/SD/m4M9NUf6', max_length=25, unique=True),
        ),
    ]
