# Generated by Django 4.0.6 on 2022-07-18 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(default='SCH/FCULT/DPT/SD/hifD2KKO', max_length=25, unique=True),
        ),
    ]
