# Generated by Django 4.0.6 on 2022-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_id_alter_customuser_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
