# Generated by Django 4.0.5 on 2022-07-15 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_rank', models.CharField(choices=[('Assistant lecturer', 'Assistant lecturer'), ('Lecturer II', 'Lecturer II'), ('Lecturer I', 'Lecturer I'), ('Senior lecturer', 'Senior lecturer'), ('Professor', 'Professor')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeerPerformanceEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee_name', models.CharField(max_length=20)),
                ('evaluators_name', models.CharField(max_length=20)),
                ('created_at', models.DateField()),
                ('good_attitude', models.CharField(help_text='comes to work with a good attitude', max_length=20)),
                ('communication', models.CharField(help_text='Communicates well with others', max_length=20)),
                ('helpful', models.CharField(help_text='Willingness to help others', max_length=20)),
                ('punctuality', models.CharField(max_length=20)),
                ('work_by_book', models.CharField(help_text='Performs job duties as described in the Employee Handbook', max_length=20)),
                ('teachability', models.CharField(help_text='Willingness to learn', max_length=20)),
                ('efficiency', models.CharField(help_text='Efficiency/work flow', max_length=20)),
                ('knowledgeable', models.CharField(help_text='Knowledge/skill set in relation to position', max_length=20)),
                ('role_fulfillment', models.CharField(max_length=300)),
                ('cooperates_with_others', models.CharField(max_length=300)),
                ('performance_comments', models.TextField()),
                ('objectives', models.TextField()),
                ('suggestions', models.TextField(help_text='Suggestions to successfully achieve objectives')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer')),
            ],
        ),
    ]
