# Generated by Django 4.0.6 on 2022-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_alter_peerperformanceevaluation_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerperformanceevaluation',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
