# Generated by Django 4.0.6 on 2022-07-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_alter_peerperformanceevaluation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('I_encourage_my_students_to_reach_new_information', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_teach_my_students_how_to_reach_new_information_and_transfer_that_information_to_others', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_review_past_classes', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_prepare_course_plans_for_my_classes', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_use_daily_life_examples_for_my_students_to_help_them_understand_more_easily', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_use_teaching_aids', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_encourage_both_individual_pair_and_group_studies_in_my_classes', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_use_different_activities_in_my_classes_to_increase_attention', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_know_all_of_my_students_names', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_try_to_find_out_abilities_of_every_student', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_communicate_with_my_students_about_their_problems_and_try_to_find_solutions_to_them', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_regularly_make_updates_about_my_students_progress_to_them_and_their_parents', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_try_to_improve_my_teaching_by_learning_new_things_about_my_field', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_work_with_colleagues_to_overcome_different_issues_and_problems_and_to_learn_new_staff', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_make_observations_on_how_colleagues_teach_to_improve_myself', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_try_to_improve_my_language_to_teach_more_effectively', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_attend_trainings_about_my_teaching_field', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('My_course_plans_are_regular_and_up_to_date', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('I_keep_records_of_my_students_learning_progress', models.CharField(choices=[('always', 'always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('Please_write_down_what_you_are_good_at', models.TextField()),
                ('What_do_you_need_to_do_to_improve_yourself', models.TextField()),
                ('What_strategies_will_you_use_to_improve_yourself', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer')),
            ],
        ),
    ]
